"""Provenance Guard — backend for classifying text as human: vs AI-written.

Endpoints:
  POST /submit  -> classify content, return attribution + confidence + label
  POST /appeal  -> contest a classification, flip status to under_review
  GET  /log     -> recent structured audit-log entries (transparency/grading)

Two independent detection signals are combined into a single calibrated
confidence score (see planning.md):
  Signal 1: Groq LLM semantic classifier  (p_ai in 0-1)
  Signal 2: Stylometric structural heuristics (p_ai in 0-1)
"""

import json
import os
import re
import sqlite3
import statistics
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

DB_PATH = os.path.join(os.path.dirname(__file__), "provenance.db")
GROQ_MODEL = "llama-3.3-70b-versatile"

# Confidence thresholds (asymmetric — see planning.md §2).
# The human band is wider than the AI band because labeling a human's work as
# AI is the costlier error on a writing platform.
AI_THRESHOLD = 0.65       # p_ai >= this -> likely_ai
HUMAN_THRESHOLD = 0.40    # p_ai <= this -> likely_human
CONFIDENT_LABEL = 0.65    # confidence >= this -> a confident (non-uncertain) label

# Signal weights when combining.
W_LLM = 0.60
W_STYLE = 0.40

app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


# --------------------------------------------------------------------------- #
# Storage
# --------------------------------------------------------------------------- #
def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS content (
            content_id   TEXT PRIMARY KEY,
            creator_id   TEXT,
            text         TEXT,
            attribution  TEXT,
            confidence   REAL,
            p_ai         REAL,
            llm_score    REAL,
            style_score  REAL,
            status       TEXT,
            created_at   TEXT
        );
        CREATE TABLE IF NOT EXISTS audit_log (
            id                INTEGER PRIMARY KEY AUTOINCREMENT,
            content_id        TEXT,
            creator_id        TEXT,
            timestamp         TEXT,
            event             TEXT,
            attribution       TEXT,
            confidence        REAL,
            p_ai              REAL,
            llm_score         REAL,
            style_score       REAL,
            signals_used      TEXT,
            status            TEXT,
            appeal_reasoning  TEXT
        );
        """
    )
    conn.commit()
    conn.close()


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace(
        "+00:00", "Z"
    )


def write_audit(entry):
    conn = get_db()
    conn.execute(
        """INSERT INTO audit_log
           (content_id, creator_id, timestamp, event, attribution, confidence,
            p_ai, llm_score, style_score, signals_used, status, appeal_reasoning)
           VALUES (:content_id, :creator_id, :timestamp, :event, :attribution,
            :confidence, :p_ai, :llm_score, :style_score, :signals_used,
            :status, :appeal_reasoning)""",
        entry,
    )
    conn.commit()
    conn.close()


# --------------------------------------------------------------------------- #
# Signal 1 — Groq LLM semantic classifier
# --------------------------------------------------------------------------- #
def llm_signal(text):
    """Return probability (0-1) that `text` is AI-generated, or None if the
    LLM signal is unavailable (no key / API error)."""
    key = os.getenv("GROQ_API_KEY")
    if not key:
        return None
    try:
        from groq import Groq

        client = Groq(api_key=key)
        prompt = (
            "You are a forensic text analyst. Assess whether the text below was "
            "written by a human or generated by an AI language model. Consider "
            "voice, specificity, irregularity, and lived detail (human) vs. "
            "hedged, evenly-balanced, generically-fluent prose (AI). "
            "Respond with ONLY a JSON object: "
            '{\"p_ai\": <float 0-1>, \"reason\": <short string>}. '
            "p_ai is your probability the text is AI-generated.\n\n"
            f"TEXT:\n{text}"
        )
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        p = float(data.get("p_ai"))
        return max(0.0, min(1.0, p))
    except Exception as exc:  # noqa: BLE001 — degrade gracefully
        app.logger.warning("LLM signal failed: %s", exc)
        return None


# --------------------------------------------------------------------------- #
# Signal 2 — Stylometric heuristics (pure Python)
# --------------------------------------------------------------------------- #
def _sentences(text):
    return [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]


def _words(text):
    return re.findall(r"[a-zA-Z']+", text.lower())


def stylometric_signal(text):
    """Return (p_ai, metrics dict). Higher p_ai => more AI-like (uniform)."""
    sentences = _sentences(text)
    words = _words(text)
    metrics = {}

    if len(words) < 8 or len(sentences) < 1:
        # Too little text for stable statistics -> sit at maximally uncertain.
        return 0.5, {"note": "insufficient_text", "word_count": len(words)}

    # 1. Sentence-length burstiness: humans vary, AI is uniform.
    lengths = [len(_words(s)) for s in sentences]
    if len(lengths) >= 2 and statistics.mean(lengths) > 0:
        cv = statistics.pstdev(lengths) / statistics.mean(lengths)  # coeff. of variation
    else:
        cv = 0.0
    metrics["sentence_len_cv"] = round(cv, 3)
    # Low variation (cv ~0.2) -> AI-like (1.0); high variation (cv ~0.8) -> human (0.0).
    burst_ai = _clamp((0.6 - cv) / 0.5)

    # 2. Type-token ratio: very low diversity (repetition) reads non-human-natural.
    ttr = len(set(words)) / len(words)
    metrics["type_token_ratio"] = round(ttr, 3)
    # Human casual writing sits mid/high TTR; very low TTR -> more AI/uniform.
    ttr_ai = _clamp((0.55 - ttr) / 0.35)

    # 3. Casual markers (contractions, dashes, ellipses, lowercase 'i').
    contractions = len(re.findall(r"\b\w+'\w+\b", text))
    dashes = text.count("—") + text.count(" - ")
    ellipses = text.count("...")
    lone_i = len(re.findall(r"\bi\b", text))  # lowercase 'i' as a word -> casual human
    casual = contractions + dashes + ellipses + lone_i
    casual_per_100w = casual / (len(words) / 100.0)
    metrics["casual_markers_per_100w"] = round(casual_per_100w, 2)
    # Many casual markers -> human (low p_ai); none -> AI-leaning.
    casual_ai = _clamp((1.5 - casual_per_100w) / 1.5)

    # Blend the three structural cues.
    p_ai = 0.45 * burst_ai + 0.30 * ttr_ai + 0.25 * casual_ai
    return _clamp(p_ai), metrics


def _clamp(x):
    return max(0.0, min(1.0, float(x)))


# --------------------------------------------------------------------------- #
# Confidence scoring + label generation
# --------------------------------------------------------------------------- #
def score(text):
    """Run both signals, combine, return a full scoring dict."""
    p_llm = llm_signal(text)
    p_style, style_metrics = stylometric_signal(text)

    signals_used = ["stylometry"]
    if p_llm is not None:
        signals_used.insert(0, "groq_llm")
        p_ai = W_LLM * p_llm + W_STYLE * p_style
        degraded = False
    else:
        # LLM unavailable -> stylometry only.
        p_ai = p_style
        degraded = True

    p_ai = _clamp(p_ai)

    # Confidence = probability of the leaning class. This stays intuitive:
    # uncertain cases (p_ai near 0.5) honestly report ~50-65%, while clear
    # cases report high values. A confident verdict needs to clear the band.
    confidence = max(p_ai, 1.0 - p_ai)

    if p_ai >= AI_THRESHOLD:
        attribution = "likely_ai"
    elif p_ai <= HUMAN_THRESHOLD:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    confidence = round(_clamp(confidence), 3)
    label = make_label(attribution, confidence)

    return {
        "p_ai": round(p_ai, 3),
        "llm_score": round(p_llm, 3) if p_llm is not None else None,
        "style_score": round(p_style, 3),
        "style_metrics": style_metrics,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals_used": signals_used,
        "degraded": degraded,
    }


def make_label(attribution, confidence):
    pct = round(confidence * 100)
    confident = confidence >= CONFIDENT_LABEL

    if attribution == "likely_ai" and confident:
        text = (
            f"🤖 Likely AI-generated — Our analysis suggests this text was "
            f"probably created with AI assistance (confidence: {pct}%). This is "
            f"an automated estimate, not a certainty. The creator can appeal "
            f"this label."
        )
        variant = "high_confidence_ai"
    elif attribution == "likely_human" and confident:
        text = (
            f"✍️ Likely human-written — Our analysis found no strong signs of AI "
            f"generation in this text (confidence: {pct}%). This is an automated "
            f"estimate, not a guarantee of authorship."
        )
        variant = "high_confidence_human"
    else:
        text = (
            f"❓ Uncertain origin — We couldn't confidently determine whether "
            f"this text was written by a human or AI (confidence: {pct}%). We're "
            f"showing this honestly rather than guessing. No attribution claim "
            f"is being made."
        )
        variant = "uncertain"

    return {"variant": variant, "text": text}


# --------------------------------------------------------------------------- #
# Endpoints
# --------------------------------------------------------------------------- #
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True) or {}
    text = (body.get("text") or "").strip()
    creator_id = body.get("creator_id")

    if not text:
        return jsonify({"error": "Field 'text' is required."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400

    content_id = str(uuid.uuid4())
    result = score(text)
    ts = now_iso()

    conn = get_db()
    conn.execute(
        """INSERT INTO content
           (content_id, creator_id, text, attribution, confidence, p_ai,
            llm_score, style_score, status, created_at)
           VALUES (?,?,?,?,?,?,?,?,?,?)""",
        (
            content_id, creator_id, text, result["attribution"],
            result["confidence"], result["p_ai"], result["llm_score"],
            result["style_score"], "classified", ts,
        ),
    )
    conn.commit()
    conn.close()

    write_audit(
        {
            "content_id": content_id,
            "creator_id": creator_id,
            "timestamp": ts,
            "event": "classification",
            "attribution": result["attribution"],
            "confidence": result["confidence"],
            "p_ai": result["p_ai"],
            "llm_score": result["llm_score"],
            "style_score": result["style_score"],
            "signals_used": json.dumps(result["signals_used"]),
            "status": "classified",
            "appeal_reasoning": None,
        }
    )

    return jsonify(
        {
            "content_id": content_id,
            "creator_id": creator_id,
            "attribution": result["attribution"],
            "confidence": result["confidence"],
            "label": result["label"],
            "signals": {
                "groq_llm": result["llm_score"],
                "stylometry": result["style_score"],
                "style_metrics": result["style_metrics"],
                "combined_p_ai": result["p_ai"],
                "signals_used": result["signals_used"],
                "degraded": result["degraded"],
            },
            "status": "classified",
        }
    )


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True) or {}
    content_id = body.get("content_id")
    reasoning = (body.get("creator_reasoning") or "").strip()

    if not content_id:
        return jsonify({"error": "Field 'content_id' is required."}), 400
    if not reasoning:
        return jsonify({"error": "Field 'creator_reasoning' is required."}), 400

    conn = get_db()
    row = conn.execute(
        "SELECT * FROM content WHERE content_id = ?", (content_id,)
    ).fetchone()
    if row is None:
        conn.close()
        return jsonify({"error": "Unknown content_id."}), 404

    conn.execute(
        "UPDATE content SET status = ? WHERE content_id = ?",
        ("under_review", content_id),
    )
    conn.commit()
    conn.close()

    ts = now_iso()
    write_audit(
        {
            "content_id": content_id,
            "creator_id": row["creator_id"],
            "timestamp": ts,
            "event": "appeal",
            # Preserve the original decision alongside the appeal.
            "attribution": row["attribution"],
            "confidence": row["confidence"],
            "p_ai": row["p_ai"],
            "llm_score": row["llm_score"],
            "style_score": row["style_score"],
            "signals_used": None,
            "status": "under_review",
            "appeal_reasoning": reasoning,
        }
    )

    return jsonify(
        {
            "content_id": content_id,
            "status": "under_review",
            "message": "Appeal received. This content is now under human review.",
            "original_decision": {
                "attribution": row["attribution"],
                "confidence": row["confidence"],
            },
        }
    )


@app.route("/log", methods=["GET"])
def log():
    limit = request.args.get("limit", default=50, type=int)
    conn = get_db()
    rows = conn.execute(
        "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    entries = []
    for r in rows:
        e = dict(r)
        if e.get("signals_used"):
            e["signals_used"] = json.loads(e["signals_used"])
        entries.append(e)
    return jsonify({"entries": entries})


@app.route("/", methods=["GET"])
def index():
    return jsonify(
        {
            "service": "Provenance Guard",
            "endpoints": ["POST /submit", "POST /appeal", "GET /log"],
        }
    )


init_db()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
